name: Build on raspbian/raspios

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [armv6l, armv7l, aarch64]
        include:
        - arch: armv6l
          cpu: arm1176
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_zero_w
        - arch: armv7l
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_zero2_w
        - arch: aarch64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        copy_repository_path: /usr/src/i2pd
        commands: |
          apt-get update -y --allow-releaseinfo-change
          apt-get install --no-install-recommends -y build-essential libboost-dev libminiupnpc-dev libssl-dev zlib1g-dev
          cd /usr/src/i2pd
          make DEBUG=no USE_GIT_VERSION=yes -j`nproc`
